# Generated by Django 2.2.5 on 2019-09-18 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('democratic_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordercrossing',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='border_crossing', to='democratic_api.Person'),
        ),
        migrations.AlterField(
            model_name='forbiddenstuff',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forbidden_stuff', to='democratic_api.Person'),
        ),
    ]
