# Generated by Django 2.2.5 on 2019-09-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democratic_api', '0002_auto_20190918_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordercrossing',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
